### ISSUE TITLE
Add quotes for rules with braces

### ISSUE THREAD

**Issue by HugoHeneault** [mow/apache2nginx#2]
Hello,

First of all, thanks for this simple and great tool !  

I think I have an issue. 

`RewriteRule ^rule([0-9]{1,3})$ rule.php?id=$1`
is converted into 
`rewrite ^/rule([0-9]{1,3})$ /rule.php?id=$1;`

But it doesn't work. 
It should output `rewrite "^/rule([0-9]{1,3})$ /rule.php?id=$1;"` to be compatible. 

Is it possible to create a fix for this ?

**Comment by HugoHeneault** [comment]
Hello, 

This issue is back, unfortunately... :(

**Comment by mow** [comment]
Hello, can you provide an example?

**Comment by HugoHeneault** [comment]
Hi, 

Of course : 

`RewriteRule ^labels\/?(update|delete)?\/([A-Za-z0-9]{10,11})$ labels.php?action=$1&public_id=$2`

Thanks ! :)

**Comment by HugoHeneault** [comment]
Any updates about this being reintegrated? I've lost half an hour trying to figuring this again. :sob:

**Comment by mow** [comment]
Done also on anilcetin.com thanks.
